# Site settings
title: d2m.tech
header-img: pages/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: d2m.tech
description: "Site web based on start bootstrap!"
# baseurl: "/d2m.tech"
# url: "https://admien33.github.io"
url: "http://startbootrap.d2m.tech"
baseurl: ""
twitter_username: 
github_username:  
facebook_username:  
email_username:  your-email@yourdomain.com
root_folder_img: /img

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Staticman
staticmanUrl: https://arcane-woodland-50389.herokuapp.com/v2/entry/admien33/d2m.tech/staticman_data/comments

